server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
  data:
    redis:
      # Leave unset to disable Redis beans
      host: ""

cors:
  allowed-origins: ["http://localhost:3000"]

app:
  cache:
    ttl-seconds: 120
